server:
  port: 8877

spring:
  cloud:
    gateway:
      routes:
        - id: demo_route
          uri: http://127.0.0.1:18083/consumer
          order: 2
          predicates:
            - Path=/demo
          filters:
            - AddResponseHeader=hello, Gateway